### ISSUE TITLE
Alias request for commands

### ISSUE THREAD

**Issue by GabrieleBattaglia** [tage64/chess-cli#1]
Hi. One of the main goal when using a CLI application is to be fast and efficient.
What I really like to have will be a shortened format for every command, like p for play, a  for analysis and so on.
The shortened form must live together the present one, so everyone can choose what to use.
The shortened form must have preferably 1 character, or 2 or 3 when is needed.

**Comment by tage64** [comment]
Good idea. I have added some aliases in the latest release (v0.1.0-alpha.7). Please let me know what you think.

**Comment by tage64** [comment]
Good idea. I've added some aliases in the latest release (v0.2.0-alpha.7). Please let me know what you think.
