### ISSUE TITLE
Idea for implementation: copy/paste.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [tage64/chess-cli#11]
Hi Tage.
To me, a good idea for a further implementation, even easy to implement would be the following.
Using pyperclip you can set a couple of commands to copy to and paste from system clipboard a FEN position or even a full PGN game or maybe a set of games.
When copy, chess-cli could ask if user want to copy the whole game or just the FEN.
When paste, you can parse the clipboard content and easlily detect if it's empty, or contain unknown stuff, or a FEN or a PGN.
Imagine how easy and confortable would be copy a game from an editor with an editor then switch on chess-cli and simple paste it in the program.
Thanks.

**Comment by tage64** [comment]
Solved by 446018a
