### ISSUE TITLE
Authorize with Lichess.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [tage64/chess-cli#12]
Thanks for previews fixing.
I'm trying to play via Lichess.
I sent the autorize command, browser opens and I click on autorize button.
Then Ms Edge says "page not found"
Gabrybat, my computer's name refuses the connection.
I cheched firewall and I have no allerts even though I don't know if I have to put manually an expection.
Any help?

**Comment by tage64** [comment]
I have no idea. There is however, no reason to authorize with Lichess yet. The only Lichess command which is implemented is `challenge`, and I don't think that it requires authorization.
