### ISSUE TITLE
Evaluation proposal.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [tage64/chess-cli#16]
"I propose modifying the references received following the analysis of the positions. Currently, the evaluations return values relative to the color that has to move. Instead, I ask you to change them using absolute values, meaning values that are not dependent on whose turn it is to move, irrespective of the color that moves.

In this way, especially in situations where the imbalance is very slight, it will be much easier to understand which of the two colors is in the lead, whether it is White's turn or Black's. I believe that an absolute evaluation, rather than a relative one, will be immediately comprehensible and much easier to read."

**Comment by tage64** [comment]
Implemented by 27708e4.
