### ISSUE TITLE
Adding turn in board command.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [tage64/chess-cli#18]
I suggest to add the who's turn to the board command.

**Comment by tage64** [comment]
I don't understand what you mean.

**Comment by GabrieleBattaglia** [comment]
Sorry to be unclear. I mean. When you give the board command and chess'cli prints out the ascii board with a resume of all pieces and their position, you may consider to add also the information on what color has to move. And, if it's black's turn, the board itself should be flipped over.

**Comment by tage64** [comment]
Fixed by 0a20a18.
