### ISSUE TITLE
Analysis returned lines

### ISSUE THREAD

**Issue by GabrieleBattaglia** [tage64/chess-cli#4]
Analysis show must be taken a parameter to specify how many lines retrieve from the engine. 

    Something like:
    analysis [s#]
Where s stands for show and the number indicates how many generated lines we want to see.
for the main line only, we could send:
    Analysis s1
or, analysis s5 to see the all five lines generated by the engine.

**Comment by tage64** [comment]
With aa545c8 it is possible to type:
```
analysis show 1
```
to only get the best line. Or `analysis show 3` to get the 3 best lines. 

Note though the maximum number of lines is the number given to `analysis start` (which defaults to 5). So if you want to get the 10 best lines you must type:
```
analysis start -n 10
```
when starting the analysis. This is how the UCI protocol works, we specify the number of moves when starting the analysis.
