### ISSUE TITLE
Problem detected by Windows defender.

### ISSUE THREAD

**Issue by GabrieleBattaglia** [tage64/chess-cli#8]
Hi. today I was trying to run the chess-cli 6 alpha compiled for Windows and Microsoft Defender detected this:
***
Published Apr 20, 2024| Updated

Trojan:Win64/LunaLogger!pz
Detected by Microsoft Defender Antivirus
Aliases:No associated aliases
Summary
Microsoft Defender Antivirus detects and removes this threat.
This threat can perform a number of actions of a malicious hacker's choice on your PC.
***

Do you think I've to worry about it?

**Comment by tage64** [comment]
I don't know, but probably not. But there is always the option to run Chess-CLI from source with poetry. The correct python version can be installed with PyEnv and activated with something like `poetry env use python3.12`.

**Comment by GabrieleBattaglia** [comment]
Is PYENV available for Win11 as well?
